name: ploy
version: 0.1.0.0
github: "goshatch/ploy"
license: BSD-3-Clause
author: "Gosha Tcherednitchenko"
maintainer: "gosha@gosha.net"
copyright: "2025 Gosha Tcherednitchenko"

extra-source-files:
    - README.md
    - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/goshatch/ploy#readme>

dependencies:
    - base >= 4.7 && < 5
    - text # efficient text processing
    - megaparsec >= 9.0 # parser combinator library
    - parser-combinators # Additional parser utilities
    - containers # Map, Set, etc.
    - mtl # Monad transformer library

ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints

default-extensions:
    - OverloadedStrings # Allows string literals for Text
    - DerivingStrategies # Explicit deriving strategies
    - LambdaCase # \case syntax
    - RecordWildCards # {..} syntax for records
    - NamedFieldPuns # Convenient record access
    - ImportQualifiedPost # Allow `import M qualified` syntax

library:
    source-dirs: src

executables:
    ploy-exe:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - ploy

tests:
    ploy-test:
        main: Spec.hs
        source-dirs: test
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - ploy
